framework:
    messenger:
        buses:
            messenger.bus.default:
                middleware: 'App\Middleware\ImagesDownloadedMiddleware'

        transports:
            image_download: 'redis://localhost:6379/images_download'
            zip_creation: 'redis://localhost:6379/zip_creation'

        routing:
            App\Message\DownloadImageMessage: image_download
            App\Message\ZipCreationMessage: zip_creation
